.SUFFIXES: .fpp .f90 .c .o
.PHONY: all 

F90FLAGS += -I ../../
LDFLAGS += -I ../../
CLAGS += -I ../../

.f90.o: 
	$(FC) $(F90FLAGS) -c $<
.fpp.f90:
	$(CPP) $(CPPFLAGS) $< $@
.c.o:
	$(CC) $(CFLAGS) -c $<



