# Host: unknown (used to be known as LINUX_xlf)

COMPILER=xl

include Makefile.BLUEGENE

include Makefile.xl

ifdef USE_MPI
	FC = mpif90.ibm
	CC = mpcc_r
endif

ifeq ($(USE_FFT),fftw)
	FFT_INC = \
	 -I//bgl/software/linux-sles9-ppc64/tools/fftw/fftw-3.1.2-double/include \
	 -I/bgl/software/linux-sles9-ppc64/tools/fftw/bglfftwgel-2.1.5-double/include
	FFT_LIB = -lfftw3 -ldfftw -ldrfftw \
	 -L/bgl/software/linux-sles9-ppc64/tools/fftw/bglfftwgel-2.1.5-double/lib \
	 -L/bgl/software/linux-sles9-ppc64/tools/fftw/fftw-3.1.2-double/lib
endif

ifdef USE_NETCDF
	NETCDF_INC = -I/bgl/software/linux-sles9-ppc64/tools/netcdf-3.6.1/include 
	NETCDF_LIB = -lnetcdf \
		   -L/bgl/software/linux-sles9-ppc64/tools/netcdf-3.6.1/lib
endif
