# Compiler: Lahey/Fujitsu Fortran

FC = 
F90FLAGS = --dbl --ml cdecl
ifeq ($(PROJECT),gs2)
	F90FLAGS_real_double_promote = --quad $(F90FLAGS)
endif

ifdef STATIC
	F90FLAGS += --staticlink
endif

ifdef DEBUG
# -mpitrace -mpianim -mpilog
	F90FLAGS += -g --chk aesu 
#	F90FLAGS += -mpitrace 
	F90OPTFLAGS =
else
	F90OPTFLAGS += -O 
endif
