# Dawson G5 cluster
CHIP=g5
include Makefile.xlf

FC = xlf95
PLATFORM_LINKS = ibm
# what for?
F90FLAGS = -qmoddir=/tmp/bdorland -I/tmp/bdorland

ifdef MPI
	MPI_INC=-I/u/local/mpi/mpilam/include
	MPI_LIB=-L/u/local/mpi/mpilam/lib -llammpio -llamf77mpi -lmpi -llam
endif
NETCDF_INC=-I/u/local/apps/netcdf/include
NETCDF_LIB=-L/u/local/apps/netcdf/lib -lnetcdf
FFT_INC=
FFT_LIB=-L/u/home2/nfl/FFTW/lib -lfftw -lrfftw
