# Host: unknown (used to be known as CPU=LINUX_abs)

COMPILER=absoft
USE_NR_RAN=on

ifeq ($(PROJECT),gs2)
	PLATFORM_LINKS = linux_abs
endif

include Makefile.$(COMPILER)

FC = mpif90

ifeq ($(USE_FFT),fftw)
	FFT_LIB = -L~kthcmr/fftw -lrfftw -lfftw 
endif

ifdef USE_NETCDF
	NETCDF_LIB = -L/usr/lib -lnetcdf
endif
