# Compiler: GNU gfortran
# Tested on Intel Mac OS X by RN
# Optimization not tested

FC = gfortran
F90FLAGS = -fdefault-real-8 -ffree-line-length-none

ifdef STATIC
	F90FLAGS += -static
endif

ifdef DEBUG
	F90FLAGS += -g -Wall -fimplicit-none -fbounds-check
#	F90FLAGS += -g -Wall -fbounds-check
	F90OPTFLAGS =
else
	F90OPTFLAGS = -O3
endif
