# Host: bassi at NERSC (IBM POWER 5)

COMPILER=xl
ifdef FFTW
	USE_FFT = fftw
else
	override USE_FFT =
endif
ifdef NETCDF
	USE_NETCDF = new
else
	override USE_NETCDF =
endif
ifdef HDF5
	USE_HDF5 = on
else
	override USE_HDF5 =
endif
ifeq ($(PROJECT),gs2)
	USE_HDF5=on
endif
ifdef STATIC
$(warning STATIC is not supported on bassi)
	override STATIC=
endif

ifeq ($(PROJECT),gs2)
	include Makefile.RS6000
endif

include Makefile.$(COMPILER)

ifdef MPI
	FC = mpxlf90_r
	CC = mpcc_r
endif

ifeq ($(USE_FFT),fftw)
	FFT_INC = $$FFTW
	ifdef DBLE
		FFT_LIB = $$FFTW -ldfftw -ldrfftw
	else
		FFT_LIB = $$FFTW -lsfftw -lsrfftw
	endif
endif

ifdef USE_NETCDF
	NETCDF_INC = -I$$NETCDF_DIR/include  
	NETCDF_LIB = $$NETCDF
endif
