# Compiler: IBM XL Fortran

#FC = xlf95
FC = xlf90
F90FLAGS = -qautodbl=dbl4 -qsuffix=f=f90
# this option makes real -> dble, and dble -> quad
F90FLAGS_real_double_promote = $(F90FLAGS) -qautodbl=dbl

ifdef STATIC
	LDFLAGS += -bstatic
endif

ifdef DEBUG
	F90FLAGS += -g -C
#	F90FLAGS += -g
# bassi (from CPU=RS6000 in old Makefile)
#	F90FLAGS += -g -qcheck -qflttrap -qinitauto=7FF7FFFF
	F90OPTFLAGS =
	LIBS	+= # $$TRACE_MPIF
else
	F90OPTFLAGS += -O3
#	F90OPTFLAGS += -O4
	ifeq ($(CHIP),g5) # dawson
		F90OPTFLAGS += -qarch=g5 -qtune=g5
	endif
	ifeq ($(CHIP),bluegene_l) # IBM Blue Gene/L
#	F90OPTFLAGS += -qarch=440d -qtune=440 -qmaxmem=6400
#	F90OPTFLAGS += -qarch=440d -qtune=440
		F90OPTFLAGS += -qstrict -qarch=440d -qtune=440
	endif
	ifeq ($(CHIP),auto) # bassi, ukaff1a
		F90OPTFLAGS += -qarch=auto -qtune=auto
	endif
endif
