
.SUFFIXES: .fpp .f90 .c .o
.PHONY: all clean

F90FLAGS += -I ../../
LDFLAGS += -I ../../
CFLAGS += -I ../../
CPPFLAGS += -I ../../

.f90.o: 
	$(FC) $(F90FLAGS) -c $<
.fpp.f90:
	$(CPP) $(CPPFLAGS) $< $@
.c.o:
	$(CC) $(CFLAGS) -c $<


clean: 
	$(CLEANCOMMAND)


RUNCOMMAND= $(TESTCOMMAND) $(1) $(BLUEGENESTUFF) $(2)

