


# Specify any required modules that are not in libgs2.a
TEST_MODS= $(GK_HEAD_DIR)/functional_tests.o  $(GK_HEAD_DIR)/libgs2.a $(GK_HEAD_DIR)/benchmarks.o

# Run the tests in all subfolders unless otherwise specified
# by setting the variable TESTS
ifdef TESTS
TESTS_TMP = $(filter $(wildcard */.),$(patsubst %,%/.,$(TESTS)))
else
TESTS_TMP = $(wildcard */.)
endif

ifdef EXCLUDE_TESTS
TESTS_ACTUAL = $(filter-out $(patsubst %,%/.,$(EXCLUDE_TESTS)),$(TESTS_TMP))
else
TESTS_ACTUAL = $(TESTS_TMP)
endif




export
     
.PHONY: all $(TESTS_ACTUAL) clean

all: $(TESTS_ACTUAL)


clean upload: 
	for d in $(TESTS_ACTUAL); \
	do \
		$(MAKE) $@ -C $$d; \
	done


$(TESTS_ACTUAL): 
	@$(MAKE) all -C $@ TEST_FOLD=$@
