! DO NOT EDIT THIS FILE
! This file is automatically generated by 
! gs2_init.rb


!> This module is analogous to the init() function
!! in Linux-based operating systems: it initialises
!! gs2 to a certain init_level. At a given init level,
!! certain modules are initialised and certain are not.
!!
!! The gs2_init module is used by gs2_main to initialise modules. A typical
!! additional use case for this module is when it is desired
!! to override a given parameter (as in the override_* functions
!! in gs2_main). Gs2 must be taken down to the appropriate 
!! init_level, where all modules which contain any of those
!! parameters are uninitialized. The override is then set
!! and gs2 is brought back up to the highest init_level.
!! 
!! As in Linux, this module cannot be used until a certain
!! basic initialization has happened (think loading the kernel).
!! This basic initialization occurs in gs2_initialize in gs2_main,
!! and set the init_level to gs2_initialized.
!!
!! This is free software released under the MIT licence.
!! Written by:
!!            Edmund Highcock (edmundhighcock@users.sourceforge.net)
module gs2_init
  public :: init_level_type
  public :: init_level_list
  public :: init
  private

  !> A type for labelling the different init
  !! levels available in gs2.
  type init_level_list_type
    !> The init_level reaches gs2
    !! when initialize_gs2 has been called.
    integer :: gs2 = 1
    integer :: theta_grid = 2
    integer :: kt_grids = 3
    integer :: gs2_layouts = 4
    integer :: gs2_save = 5
    integer :: run_parameters = 6
    integer :: hyper = 7
    integer :: init_g = 8
    integer :: species = 9
    integer :: le_grids = 10
    integer :: dist_fn_layouts = 11
    integer :: nonlinear_terms = 12
    integer :: collisions = 13
    integer :: dist_fn = 14
    integer :: antenna = 15
    integer :: fields = 16
  end type init_level_list_type

  type(init_level_list_type) :: init_level_list
  
  !> A type for storing the init_level of gs2.
  type init_level_type
    !> The current init level
    integer :: level = 0
    !> A list of possible init levels
    !type(init_level_list_type) :: levels
  end type init_level_type
contains
  !> Initialize gs2 to the level of target_level.
  !! The init_level_type current contains info
  !! about the current initialization level. At the end
  !! of the subroutine, current%level is set to target_level
  subroutine init(current, target_level)
    use fields, only: init_fields
    implicit none
    type(init_level_type), intent(inout) :: current
    integer, intent(in) :: target_level
    integer :: i
    logical :: up, down
    down = (target_level<current%level) 
    up = (target_level>current%level) 

    if (current%level .lt. init_level_list%gs2) then
      write (*,*) "gs2_init::init cannot be called before &
       & initialize_gs2 in gs2 main"
      stop 1
    end if 


    if (current%level .eq. target_level) then
      return
    else
      if (up) then 
        if (current%level < init_level_list%theta_grid) call theta_grid
        if (current%level < init_level_list%kt_grids) call kt_grids
        if (current%level < init_level_list%gs2_layouts) call gs2_layouts
        if (current%level < init_level_list%gs2_save) call gs2_save
        if (current%level < init_level_list%run_parameters) call run_parameters
        if (current%level < init_level_list%hyper) call hyper
        if (current%level < init_level_list%init_g) call init_g
        if (current%level < init_level_list%species) call species
        if (current%level < init_level_list%le_grids) call le_grids
        if (current%level < init_level_list%dist_fn_layouts) call dist_fn_layouts
        if (current%level < init_level_list%nonlinear_terms) call nonlinear_terms
        if (current%level < init_level_list%collisions) call collisions
        if (current%level < init_level_list%dist_fn) call dist_fn
        if (current%level < init_level_list%antenna) call antenna
        if (current%level < init_level_list%fields) call fields
      else
        if (current%level > init_level_list%fields) call fields
        if (current%level > init_level_list%antenna) call antenna
        if (current%level > init_level_list%dist_fn) call dist_fn
        if (current%level > init_level_list%collisions) call collisions
        if (current%level > init_level_list%nonlinear_terms) call nonlinear_terms
        if (current%level > init_level_list%dist_fn_layouts) call dist_fn_layouts
        if (current%level > init_level_list%le_grids) call le_grids
        if (current%level > init_level_list%species) call species
        if (current%level > init_level_list%init_g) call init_g
        if (current%level > init_level_list%hyper) call hyper
        if (current%level > init_level_list%run_parameters) call run_parameters
        if (current%level > init_level_list%gs2_save) call gs2_save
        if (current%level > init_level_list%gs2_layouts) call gs2_layouts
        if (current%level > init_level_list%kt_grids) call kt_grids
        if (current%level > init_level_list%theta_grid) call theta_grid
      end if
    end if
    contains
      subroutine theta_grid
        use unit_tests, only: debug_message
        use theta_grid, only: init_theta_grid
        use theta_grid, only: finish_theta_grid
        if (up) call init_theta_grid
        if (down) call finish_theta_grid
       
        if (up) call debug_message(2, 'gs2_init::init reached init level... theta_grid   ')
        if (down) call debug_message(2, 'gs2_init::init left init level... theta_grid   ')
      end subroutine theta_grid

      subroutine kt_grids
        use unit_tests, only: debug_message
        use kt_grids, only: init_kt_grids
        use kt_grids, only: finish_kt_grids
        if (up) call init_kt_grids
        if (down) call finish_kt_grids
       
        if (up) call debug_message(2, 'gs2_init::init reached init level... kt_grids   ')
        if (down) call debug_message(2, 'gs2_init::init left init level... kt_grids   ')
      end subroutine kt_grids

      subroutine gs2_layouts
        use unit_tests, only: debug_message
        use gs2_layouts, only: init_gs2_layouts
        use gs2_layouts, only: finish_gs2_layouts
        if (up) call init_gs2_layouts
        if (down) call finish_gs2_layouts
       
        if (up) call debug_message(2, 'gs2_init::init reached init level... gs2_layouts   ')
        if (down) call debug_message(2, 'gs2_init::init left init level... gs2_layouts   ')
      end subroutine gs2_layouts

      subroutine gs2_save
        use unit_tests, only: debug_message
        use gs2_save, only: init_gs2_save
        use gs2_save, only: finish_gs2_save
        if (up) call init_gs2_save
        if (down) call finish_gs2_save
       
        if (up) call debug_message(2, 'gs2_init::init reached init level... gs2_save   ')
        if (down) call debug_message(2, 'gs2_init::init left init level... gs2_save   ')
      end subroutine gs2_save

      subroutine run_parameters
        use unit_tests, only: debug_message
        use run_parameters, only: init_run_parameters
        use run_parameters, only: finish_run_parameters
        if (up) call init_run_parameters
        if (down) call finish_run_parameters
       
        if (up) call debug_message(2, 'gs2_init::init reached init level... run_parameters   ')
        if (down) call debug_message(2, 'gs2_init::init left init level... run_parameters   ')
      end subroutine run_parameters

      subroutine hyper
        use unit_tests, only: debug_message
        use hyper, only: init_hyper
        use hyper, only: finish_hyper
        if (up) call init_hyper
        if (down) call finish_hyper
       
        if (up) call debug_message(2, 'gs2_init::init reached init level... hyper   ')
        if (down) call debug_message(2, 'gs2_init::init left init level... hyper   ')
      end subroutine hyper

      subroutine init_g
        use unit_tests, only: debug_message
        use init_g, only: init_init_g
        use init_g, only: finish_init_g
        if (up) call init_init_g
        if (down) call finish_init_g
       
        if (up) call debug_message(2, 'gs2_init::init reached init level... init_g   ')
        if (down) call debug_message(2, 'gs2_init::init left init level... init_g   ')
      end subroutine init_g

      subroutine species
        use unit_tests, only: debug_message
        use species, only: init_species
        use species, only: finish_species
        if (up) call init_species
        if (down) call finish_species
       
        if (up) call debug_message(2, 'gs2_init::init reached init level... species   ')
        if (down) call debug_message(2, 'gs2_init::init left init level... species   ')
      end subroutine species

      subroutine le_grids
        use unit_tests, only: debug_message
        use le_grids, only: init_le_grids
        use le_grids, only: finish_le_grids
        logical :: dummy1, dummy2
        if (up) call init_le_grids(dummy1, dummy2)
        if (down) call finish_le_grids
       
        if (up) call debug_message(2, 'gs2_init::init reached init level... le_grids   ')
        if (down) call debug_message(2, 'gs2_init::init left init level... le_grids   ')
      end subroutine le_grids

      subroutine dist_fn_layouts
        use unit_tests, only: debug_message
        use gs2_layouts, only: init_dist_fn_layouts
        use gs2_layouts, only: finish_dist_fn_layouts
        use kt_grids, only: naky, ntheta0
        use le_grids, only: nlambda, negrid
        use species, only: nspec
        if (up) call init_dist_fn_layouts(naky, ntheta0, nlambda, negrid, nspec) 
        if (down) call finish_dist_fn_layouts
       
        if (up) call debug_message(2, 'gs2_init::init reached init level... dist_fn_layouts   ')
        if (down) call debug_message(2, 'gs2_init::init left init level... dist_fn_layouts   ')
      end subroutine dist_fn_layouts

      subroutine nonlinear_terms
        use unit_tests, only: debug_message
        use nonlinear_terms, only: init_nonlinear_terms
        use nonlinear_terms, only: finish_nonlinear_terms
        if (up) call init_nonlinear_terms
        if (down) call finish_nonlinear_terms
       
        if (up) call debug_message(2, 'gs2_init::init reached init level... nonlinear_terms   ')
        if (down) call debug_message(2, 'gs2_init::init left init level... nonlinear_terms   ')
      end subroutine nonlinear_terms

      subroutine collisions
        use unit_tests, only: debug_message
        use collisions, only: init_collisions
        use collisions, only: finish_collisions
        if (up) call init_collisions
        if (down) call finish_collisions
       
        if (up) call debug_message(2, 'gs2_init::init reached init level... collisions   ')
        if (down) call debug_message(2, 'gs2_init::init left init level... collisions   ')
      end subroutine collisions

      subroutine dist_fn
        use unit_tests, only: debug_message
        use dist_fn, only: init_dist_fn
        use dist_fn, only: finish_dist_fn
        if (up) call init_dist_fn
        if (down) call finish_dist_fn
       
        if (up) call debug_message(2, 'gs2_init::init reached init level... dist_fn   ')
        if (down) call debug_message(2, 'gs2_init::init left init level... dist_fn   ')
      end subroutine dist_fn

      subroutine antenna
        use unit_tests, only: debug_message
        use antenna, only: init_antenna
        use antenna, only: finish_antenna
        if (up) call init_antenna
        if (down) call finish_antenna
       
        if (up) call debug_message(2, 'gs2_init::init reached init level... antenna   ')
        if (down) call debug_message(2, 'gs2_init::init left init level... antenna   ')
      end subroutine antenna

      subroutine fields
        use unit_tests, only: debug_message
        use fields, only: init_fields
        use fields, only: finish_fields
        if (up) call init_fields
        if (down) call finish_fields
       
        if (up) call debug_message(2, 'gs2_init::init reached init level... fields   ')
        if (down) call debug_message(2, 'gs2_init::init left init level... fields   ')
      end subroutine fields

  end subroutine init
end module gs2_init

