! DO NOT EDIT THIS FILE
! This file is automatically generated by overrides.rb

module overrides
  type miller_geometry_overrides_type
    logical :: set = .false.
    logical :: override_rhoc
    logical :: override_qinp
    logical :: override_shat
    logical :: override_rgeo_lcfs
    logical :: override_rgeo_local
    logical :: override_akappa
    logical :: override_akappri
    logical :: override_tri
    logical :: override_tripri
    logical :: override_shift
    logical :: override_betaprim
    real :: rhoc
    real :: qinp
    real :: shat
    real :: rgeo_lcfs
    real :: rgeo_local
    real :: akappa
    real :: akappri
    real :: tri
    real :: tripri
    real :: shift
    real :: betaprim
  end type miller_geometry_overrides_type


  type profiles_overrides_type
    logical :: set = .false.
    logical, dimension(:), pointer :: override_dens
    logical, dimension(:), pointer :: override_temp
    logical, dimension(:), pointer :: override_tprim
    logical, dimension(:), pointer :: override_fprim
    logical, dimension(:), pointer :: override_vnewk
    logical :: override_g_exb
    logical :: override_mach
    real, dimension(:), pointer :: dens
    real, dimension(:), pointer :: temp
    real, dimension(:), pointer :: tprim
    real, dimension(:), pointer :: fprim
    real, dimension(:), pointer :: vnewk
    real :: g_exb
    real :: mach
  end type profiles_overrides_type



contains
  subroutine init_miller_geometry_overrides(overrides)
    type(miller_geometry_overrides_type), intent(inout) :: overrides
    overrides%set = .true.
    overrides%override_rhoc = .false.
    overrides%override_qinp = .false.
    overrides%override_shat = .false.
    overrides%override_rgeo_lcfs = .false.
    overrides%override_rgeo_local = .false.
    overrides%override_akappa = .false.
    overrides%override_akappri = .false.
    overrides%override_tri = .false.
    overrides%override_tripri = .false.
    overrides%override_shift = .false.
    overrides%override_betaprim = .false.
  end subroutine init_miller_geometry_overrides


  subroutine finish_miller_geometry_overrides(overrides)
    type(miller_geometry_overrides_type), intent(inout) :: overrides
    overrides%set = .false.
    overrides%override_rhoc = .false.
    overrides%override_qinp = .false.
    overrides%override_shat = .false.
    overrides%override_rgeo_lcfs = .false.
    overrides%override_rgeo_local = .false.
    overrides%override_akappa = .false.
    overrides%override_akappri = .false.
    overrides%override_tri = .false.
    overrides%override_tripri = .false.
    overrides%override_shift = .false.
    overrides%override_betaprim = .false.
  end subroutine finish_miller_geometry_overrides


  subroutine init_profiles_overrides(overrides, nspec)
    integer, intent(in) :: nspec
    type(profiles_overrides_type), intent(inout) :: overrides
    overrides%set = .true.
    allocate(overrides%override_dens(nspec), overrides%dens(nspec))
    overrides%override_dens = .false.
    allocate(overrides%override_temp(nspec), overrides%temp(nspec))
    overrides%override_temp = .false.
    allocate(overrides%override_tprim(nspec), overrides%tprim(nspec))
    overrides%override_tprim = .false.
    allocate(overrides%override_fprim(nspec), overrides%fprim(nspec))
    overrides%override_fprim = .false.
    allocate(overrides%override_vnewk(nspec), overrides%vnewk(nspec))
    overrides%override_vnewk = .false.
    overrides%override_g_exb = .false.
    overrides%override_mach = .false.
  end subroutine init_profiles_overrides


  subroutine finish_profiles_overrides(overrides)
    type(profiles_overrides_type), intent(inout) :: overrides
    overrides%set = .false.
    deallocate(overrides%override_dens, overrides%dens)
    overrides%override_dens = .false.
    deallocate(overrides%override_temp, overrides%temp)
    overrides%override_temp = .false.
    deallocate(overrides%override_tprim, overrides%tprim)
    overrides%override_tprim = .false.
    deallocate(overrides%override_fprim, overrides%fprim)
    overrides%override_fprim = .false.
    deallocate(overrides%override_vnewk, overrides%vnewk)
    overrides%override_vnewk = .false.
    overrides%override_g_exb = .false.
    overrides%override_mach = .false.
  end subroutine finish_profiles_overrides



end module overrides
