#!/bin/bash
PREC="-p 4,8"
if [[ $1 != *"-p"* ]]
then 
  PREC1=$PREC
fi 
if [[ $2 != *"-p"* ]]
then 
  PREC2=$PREC
fi 
if [ "$(./getncdat $1 $PREC1)" = "$(./getncdat $2 $PREC2)" ] 
then
	echo "T" > tmpdata.dat
else
	echo "F" > tmpdata.dat
fi
