
.SUFFIXES: .fpp .f90 .c .o
.PHONY: all clean

#$(info "F90FLAGS is $(F90FLAGS)")
#F90FLAGS = $(F90FLAGS) -I ../../
#$(info "F90FLAGS is $(F90FLAGS)")
#LDFLAGS += -I ../../
#CFLAGS += -I ../../
#CPPFLAGS += -I ../../

.f90.o: 
	$(FC) $(F90FLAGS) -c $< -I $(GK_HEAD_DIR)
.fpp.f90:
	$(CPP) $(CPPFLAGS) $< $@ -I $(GK_HEAD_DIR)
.c.o:
	$(CC) $(CFLAGS) -c $< -I $(GK_HEAD_DIR)
	
# This prevents error messages like m2c: Command not found
%.o : %.mod


clean: 
	$(CLEANCOMMAND)

upload:
	$(UPLOADCOMMAND)


RUNCOMMAND= @$(TESTCOMMAND)$(1) $(BLUEGENEARGS) $(2) $(3); if test "$$?" != 0; then  echo "FAILED: `basename $$PWD` ($(1) $(2) $(3))" >> results_of_test.txt; else echo "passed: `basename $$PWD` ($(TESTCOMMAND)$(1) $(2) $(3))" >> results_of_test.txt;  fi


BENCHMARKCOMMAND= $(call TESTEXEC,$(1))$(2) $(BLUEGENEARGS) $(3)

UPLOAD_BENCHMARKS= ls $(1) | xargs -n 1 -I {} scp {} $(USER),gyrokinetics@web.sourceforge.net:htdocs/wikifiles/benchmark_data/.
