
!> DO NOT EDIT THIS FILE
!! This file has been automatically generated using generate_diagnostics_config.rb

!> A module for handling the configuration of the diagnostics
!! module via the namelist diagnostics_config.
module diagnostics_config

  use simpledataio, only: sdatio_file
  use diagnostics_ascii, only: diagnostics_ascii_type



  public :: init_diagnostics_config
  public :: finish_diagnostics_config
  public ::diagnostics_type
  public :: results_summary_type


  !> A type for storing the current results of the simulation
  type results_summary_type
    real :: phi2
    real :: apar2
    real :: bpar2
    real :: total_heat_flux
    real :: total_momentum_flux
    real :: total_particle_flux
    real :: max_growth_rate

    ! Individual heat fluxes
    real, dimension(:), allocatable :: species_es_heat_flux
    real, dimension(:), allocatable :: species_apar_heat_flux
    real, dimension(:), allocatable :: species_bpar_heat_flux

    ! Total fluxes
    real, dimension(:), allocatable :: species_heat_flux
    real, dimension(:), allocatable :: species_momentum_flux
    real, dimension(:), allocatable :: species_particle_flux
    real, dimension(:), allocatable :: species_energy_exchange

    ! Average total fluxes
    real, dimension(:), allocatable :: species_heat_flux_avg
    real, dimension(:), allocatable :: species_momentum_flux_avg
    real, dimension(:), allocatable :: species_particle_flux_avg

    ! Heating
    real, dimension(:), allocatable :: species_heating
    real, dimension(:), allocatable :: species_heating_avg
  end type results_summary_type

  !> A type for storing the diagnostics configuration,
  !! a reference to the output file, and current 
  !! results of the simulation
  type diagnostics_type
   type(sdatio_file) :: sfile
   !type(sdatio_file) :: sfilemovie
   type(diagnostics_ascii_type) :: ascii_files
   type(results_summary_type) :: current_results
   !> Integer below gives the sdatio type 
   !! which corresponds to a gs2 real
   integer :: rtype
   integer :: istep
   logical :: create
   logical :: wryte
   logical :: distributed
   logical :: parallel
   logical :: exit
   logical :: vary_vnew_only
   logical :: calculate_fluxes
   real :: user_time
   real :: user_time_old
   real, dimension(:), allocatable :: fluxfac
   integer :: nwrite
   integer :: nwrite_large
   logical :: write_any
   integer :: igomega
   logical :: print_line
   logical :: print_flux_line
   logical :: write_fields
   logical :: write_phi_over_time
   logical :: write_apar_over_time
   logical :: write_bpar_over_time
   logical :: write_movie
   logical :: write_moments
   logical :: write_fluxes
   logical :: write_fluxes_by_mode
   logical :: write_omega
   integer :: navg
   real :: omegatinst
   real :: omegatol
   logical :: exit_when_converged
   logical :: write_verr
   logical :: write_max_verr
   integer :: ncheck
   logical :: write_heating
   logical :: write_ascii
   logical :: write_gyx
   logical :: write_g
   logical :: write_lpoly
   integer :: conv_nstep_av
   real :: conv_test_multiplier
   integer :: conv_min_step
   integer :: conv_max_step
   integer :: conv_nsteps_converged
   logical :: use_nonlin_convergence
   logical :: write_cross_phase
   logical :: write_jext
  end type diagnostics_type


  private

contains
  subroutine init_diagnostics_config(gnostics)
    use file_utils, only: open_output_file
    type(diagnostics_type), intent(out) :: gnostics
    call read_parameters(gnostics)
    call allocate_current_results(gnostics)
  end subroutine init_diagnostics_config

  subroutine finish_diagnostics_config(gnostics)
    type(diagnostics_type), intent(out) :: gnostics
    call deallocate_current_results(gnostics)
  end subroutine finish_diagnostics_config

  subroutine allocate_current_results(gnostics)
    use species, only: nspec
    type(diagnostics_type), intent(inout) :: gnostics
    allocate(gnostics%current_results%species_es_heat_flux(nspec))
    allocate(gnostics%current_results%species_apar_heat_flux(nspec))
    allocate(gnostics%current_results%species_bpar_heat_flux(nspec))

    allocate(gnostics%current_results%species_heat_flux(nspec))
    allocate(gnostics%current_results%species_momentum_flux(nspec))
    allocate(gnostics%current_results%species_particle_flux(nspec))
    allocate(gnostics%current_results%species_energy_exchange(nspec))
    allocate(gnostics%current_results%species_heat_flux_avg(nspec))
    allocate(gnostics%current_results%species_momentum_flux_avg(nspec))
    allocate(gnostics%current_results%species_particle_flux_avg(nspec))
    allocate(gnostics%current_results%species_heating(nspec))
    allocate(gnostics%current_results%species_heating_avg(nspec))
  end subroutine allocate_current_results

  subroutine deallocate_current_results(gnostics)
    type(diagnostics_type), intent(inout) :: gnostics
    ! This routine needs to be fixed: I don't know 
    ! how to correctly deallocate the derived type
    return
    
    ! One call deallocates gnostics and all allocatable arrays 
    ! within it
    !deallocate(gnostics%current_results)
    write (*,*) "DEALLOCATING"
    deallocate(gnostics%current_results%species_heat_flux)
    deallocate(gnostics%current_results%species_momentum_flux)
    deallocate(gnostics%current_results%species_particle_flux)
    deallocate(gnostics%current_results%species_heat_flux_avg)
    deallocate(gnostics%current_results%species_momentum_flux_avg)
    deallocate(gnostics%current_results%species_particle_flux_avg)
    deallocate(gnostics%current_results%species_heating)
    deallocate(gnostics%current_results%species_heating_avg)
  end subroutine deallocate_current_results


  subroutine read_parameters(gnostics)
    use file_utils, only: input_unit, error_unit, input_unit_exist
    use text_options, only: text_option, get_option_value
    use mp, only: proc0, broadcast
    implicit none
    type(diagnostics_type), intent(out) :: gnostics
    integer :: nwrite
    integer :: nwrite_large
    logical :: write_any
    integer :: igomega
    logical :: print_line
    logical :: print_flux_line
    logical :: write_fields
    logical :: write_phi_over_time
    logical :: write_apar_over_time
    logical :: write_bpar_over_time
    logical :: write_movie
    logical :: write_moments
    logical :: write_fluxes
    logical :: write_fluxes_by_mode
    logical :: write_omega
    integer :: navg
    real :: omegatinst
    real :: omegatol
    logical :: exit_when_converged
    logical :: write_verr
    logical :: write_max_verr
    integer :: ncheck
    logical :: write_heating
    logical :: write_ascii
    logical :: write_gyx
    logical :: write_g
    logical :: write_lpoly
    integer :: conv_nstep_av
    real :: conv_test_multiplier
    integer :: conv_min_step
    integer :: conv_max_step
    integer :: conv_nsteps_converged
    logical :: use_nonlin_convergence
    logical :: write_cross_phase
    logical :: write_jext
    namelist /diagnostics_config/ &
      nwrite, &
      nwrite_large, &
      write_any, &
      igomega, &
      print_line, &
      print_flux_line, &
      write_fields, &
      write_phi_over_time, &
      write_apar_over_time, &
      write_bpar_over_time, &
      write_movie, &
      write_moments, &
      write_fluxes, &
      write_fluxes_by_mode, &
      write_omega, &
      navg, &
      omegatinst, &
      omegatol, &
      exit_when_converged, &
      write_verr, &
      write_max_verr, &
      ncheck, &
      write_heating, &
      write_ascii, &
      write_gyx, &
      write_g, &
      write_lpoly, &
      conv_nstep_av, &
      conv_test_multiplier, &
      conv_min_step, &
      conv_max_step, &
      conv_nsteps_converged, &
      use_nonlin_convergence, &
      write_cross_phase, &
      write_jext

    integer :: in_file
    logical :: exist

    if (proc0) then
      nwrite = 10
      nwrite_large = 100
      write_any = .true.
      igomega = 0
      print_line = .false.
      print_flux_line = .false.
      write_fields = .true.
      write_phi_over_time = .false.
      write_apar_over_time = .false.
      write_bpar_over_time = .false.
      write_movie = .false.
      write_moments = .true.
      write_fluxes = .true.
      write_fluxes_by_mode = .false.
      write_omega = .true.
      navg = 10
      omegatinst = 1.0e6
      omegatol = -0.001
      exit_when_converged = .true.
      write_verr = .true.
      write_max_verr = .false.
      ncheck = 10
      write_heating = .false.
      write_ascii = .true.
      write_gyx = .false.
      write_g = .false.
      write_lpoly = .false.
      conv_nstep_av = 4000
      conv_test_multiplier = 4e-1
      conv_min_step = 4000
      conv_max_step = 80000
      conv_nsteps_converged = 10000
      use_nonlin_convergence = .false.
      write_cross_phase = .false.
      write_jext = .false.

      in_file = input_unit_exist ("diagnostics_config", exist)
      if (exist) read (unit=in_file, nml=diagnostics_config)

      gnostics%nwrite = nwrite
      gnostics%nwrite_large = nwrite_large
      gnostics%write_any = write_any
      gnostics%igomega = igomega
      gnostics%print_line = print_line
      gnostics%print_flux_line = print_flux_line
      gnostics%write_fields = write_fields
      gnostics%write_phi_over_time = write_phi_over_time
      gnostics%write_apar_over_time = write_apar_over_time
      gnostics%write_bpar_over_time = write_bpar_over_time
      gnostics%write_movie = write_movie
      gnostics%write_moments = write_moments
      gnostics%write_fluxes = write_fluxes
      gnostics%write_fluxes_by_mode = write_fluxes_by_mode
      gnostics%write_omega = write_omega
      gnostics%navg = navg
      gnostics%omegatinst = omegatinst
      gnostics%omegatol = omegatol
      gnostics%exit_when_converged = exit_when_converged
      gnostics%write_verr = write_verr
      gnostics%write_max_verr = write_max_verr
      gnostics%ncheck = ncheck
      gnostics%write_heating = write_heating
      gnostics%write_ascii = write_ascii
      gnostics%write_gyx = write_gyx
      gnostics%write_g = write_g
      gnostics%write_lpoly = write_lpoly
      gnostics%conv_nstep_av = conv_nstep_av
      gnostics%conv_test_multiplier = conv_test_multiplier
      gnostics%conv_min_step = conv_min_step
      gnostics%conv_max_step = conv_max_step
      gnostics%conv_nsteps_converged = conv_nsteps_converged
      gnostics%use_nonlin_convergence = use_nonlin_convergence
      gnostics%write_cross_phase = write_cross_phase
      gnostics%write_jext = write_jext

    end if

    call broadcast (gnostics%nwrite)
    call broadcast (gnostics%nwrite_large)
    call broadcast (gnostics%write_any)
    call broadcast (gnostics%igomega)
    call broadcast (gnostics%print_line)
    call broadcast (gnostics%print_flux_line)
    call broadcast (gnostics%write_fields)
    call broadcast (gnostics%write_phi_over_time)
    call broadcast (gnostics%write_apar_over_time)
    call broadcast (gnostics%write_bpar_over_time)
    call broadcast (gnostics%write_movie)
    call broadcast (gnostics%write_moments)
    call broadcast (gnostics%write_fluxes)
    call broadcast (gnostics%write_fluxes_by_mode)
    call broadcast (gnostics%write_omega)
    call broadcast (gnostics%navg)
    call broadcast (gnostics%omegatinst)
    call broadcast (gnostics%omegatol)
    call broadcast (gnostics%exit_when_converged)
    call broadcast (gnostics%write_verr)
    call broadcast (gnostics%write_max_verr)
    call broadcast (gnostics%ncheck)
    call broadcast (gnostics%write_heating)
    call broadcast (gnostics%write_ascii)
    call broadcast (gnostics%write_gyx)
    call broadcast (gnostics%write_g)
    call broadcast (gnostics%write_lpoly)
    call broadcast (gnostics%conv_nstep_av)
    call broadcast (gnostics%conv_test_multiplier)
    call broadcast (gnostics%conv_min_step)
    call broadcast (gnostics%conv_max_step)
    call broadcast (gnostics%conv_nsteps_converged)
    call broadcast (gnostics%use_nonlin_convergence)
    call broadcast (gnostics%write_cross_phase)
    call broadcast (gnostics%write_jext)



  end subroutine read_parameters
end module diagnostics_config



