


# Specify any required modules that are not in libgs2.a
TEST_MODS= ../../functional_tests.o 

# Run the tests in all subfolders unless otherwise specified
# by setting the variable TESTS
ifdef TESTS
TESTS_ACTUAL = $(filter $(wildcard */.),$(patsubst %,%/.,$(TESTS)))
else
TESTS_ACTUAL = $(wildcard */.)
endif



export
     
.PHONY: all $(TESTS_ACTUAL) clean

all: $(TESTS_ACTUAL)


clean upload: 
	for d in $(TESTS_ACTUAL); \
	do \
		$(MAKE) $@ -C $$d; \
	done


$(TESTS_ACTUAL): 
	$(MAKE) all -C $@
