
!> DO NOT EDIT THIS FILE
!! This file has been automatically generated using generate_diagnostics_config.rb

!> A module for handling the configuration of the diagnostics
!! module via the namelist diagnostics_config.
module diagnostics_config

  use simpledataio, only: sdatio_file

  public :: init_diagnostics_config
  public :: finish_diagnostics_config
  public ::diagnostics_type

  type diagnostics_type
   type(sdatio_file) :: sfile
   !> Integer below gives the sdatio type 
   !! which corresponds to a gs2 real
   integer :: rtype
   integer :: istep
   logical :: create
   logical :: wryte
   logical :: distributed
   logical :: parallel
   integer :: nwrite
   logical :: write_any
   logical :: write_fields
   logical :: write_phi_over_time
   logical :: write_apar_over_time
   logical :: write_bpar_over_time
   logical :: write_fluxes
   logical :: write_fluxes_by_mode
   logical :: write_omega
  end type diagnostics_type


  private

contains
  subroutine init_diagnostics_config(gnostics)
    use file_utils, only: open_output_file
    type(diagnostics_type), intent(out) :: gnostics
    call read_parameters(gnostics)
  end subroutine init_diagnostics_config

  subroutine finish_diagnostics_config
  end subroutine finish_diagnostics_config

  subroutine read_parameters(gnostics)
    use file_utils, only: input_unit, error_unit, input_unit_exist
    use text_options, only: text_option, get_option_value
    use mp, only: proc0, broadcast
    implicit none
    type(diagnostics_type), intent(out) :: gnostics
    integer :: nwrite
    logical :: write_any
    logical :: write_fields
    logical :: write_phi_over_time
    logical :: write_apar_over_time
    logical :: write_bpar_over_time
    logical :: write_fluxes
    logical :: write_fluxes_by_mode
    logical :: write_omega
    namelist /diagnostics_config/ &
      nwrite, &
      write_any, &
      write_fields, &
      write_phi_over_time, &
      write_apar_over_time, &
      write_bpar_over_time, &
      write_fluxes, &
      write_fluxes_by_mode, &
      write_omega

    integer :: in_file
    logical :: exist

    if (proc0) then
      nwrite = 10
      write_any = .true.
      write_fields = .true.
      write_phi_over_time = .false.
      write_apar_over_time = .false.
      write_bpar_over_time = .false.
      write_fluxes = .true.
      write_fluxes_by_mode = .false.
      write_omega = .false.

      in_file = input_unit_exist ("diagnostics_config", exist)
      if (exist) read (unit=in_file, nml=diagnostics_config)

      gnostics%nwrite = nwrite
      gnostics%write_any = write_any
      gnostics%write_fields = write_fields
      gnostics%write_phi_over_time = write_phi_over_time
      gnostics%write_apar_over_time = write_apar_over_time
      gnostics%write_bpar_over_time = write_bpar_over_time
      gnostics%write_fluxes = write_fluxes
      gnostics%write_fluxes_by_mode = write_fluxes_by_mode
      gnostics%write_omega = write_omega

    end if

    call broadcast (gnostics%nwrite)
    call broadcast (gnostics%write_any)
    call broadcast (gnostics%write_fields)
    call broadcast (gnostics%write_phi_over_time)
    call broadcast (gnostics%write_apar_over_time)
    call broadcast (gnostics%write_bpar_over_time)
    call broadcast (gnostics%write_fluxes)
    call broadcast (gnostics%write_fluxes_by_mode)
    call broadcast (gnostics%write_omega)



  end subroutine read_parameters
end module diagnostics_config



