#!/bin/bash
PREC="-p 7,13"
if [[ $1 != *"-p"* ]]
then 
  PREC1=$PREC
fi 
if [[ $2 != *"-p"* ]]
then 
  PREC2=$PREC
fi 
if [ "$(./getncdat $1 $PREC1)" = "$(./getncdat $2 $PREC2)" ] 
then
	echo "T" > test_tmp.txt
else
	echo "F" > test_tmp.txt
fi
