gs2_all: modules gs2 ingen rungridgen

gs2: $(gs2_mod)
	$(LD) $(LDFLAGS) -o $@ $^ $(LIBS)

gs2.x: $(gs2_mod)
	$(LD) $(LDFLAGS) -o $@ $^ $(LIBS)

ingen: $(ingen_mod)
	$(LD) $(LDFLAGS) -o $@ $^ $(LIBS)

rungridgen: $(rungridgen_mod)
	$(LD) $(LDFLAGS) -o $@ $^ $(LIBS)

regress: $(drive_mod)
	$(LD) $(LDFLAGS) -o $@ $^ $(LIBS)

slice_g: $(slice_g_mod)
	$(LD) $(LDFLAGS) -o $@ $^ $(LIBS)

distclean:
	-rm -f gs2 gs2.x
	-rm -f ingen rungridgen regress
	-rm -f ball eiktest
