# MIT Linux cluster with NAG f95
MPI=on

include Makefile.LINUX

include Makefile.nag

ifdef MPI
	FC = mpif90
	MPI_INC = -I/opt/mpich.gccf95-2/include
endif

NETCDF_LIB = -L/usr/local/lib -lnetcdf
FFT_LIB = -L/usr/local/lib -lfftw -lrfftw
