# Compiler: Absoft Fortran

FC =
F90FLAGS = -Rp -N113

ifdef STATIC
endif

ifdef DEBUG
	F90FLAGS += -g -Rbcs
	F90OPTFLAGS =
else
	F90OPTFLAGS += -O 
endif

F90FLAGS_SFX0 = -YEXT_SFX= 
F90FLAGS_SFX1 = -YEXT_SFX=_
F90FLAGS_SFX2 = -YEXT_SFX=__
