# Compiler: Cray Fortran

FC = f90

F90FLAGS =  -M1110
CPPFLAGS += -DFCOMPILER=_CRAY_

ifdef STATIC
endif

ifdef DEBUG
	F90FLAGS += -g -R abcs -e i
	LIBS += -Wl"-D preset=inf" # -lmalloc
else
	F90OPTFLAGS += -O vector3  
endif
