# Host: unknown (used to be known as CPU=ALPHA_nag)

COMPILER=nag
USE_NR_RAN=on

ifeq ($(PROJECT),gs2)
	PLATFORM_LINKS = alpha_nag
endif

include Makefile.nag

FC = /usr/local/bin/f95

ifdef DEBUG
	F90FLAGS = -C -hpf -r8 -g90 -dusty
else
	F90FLAGS = -C -hpf -r8 -dusty
	F90FLAGS += -O
endif
