# Host: unknown (used to be known as CPU=LINUX_ifort)
# ?? Cambridge public machine ??

CHIP=pentium4

ifeq ($(PROJECT),gs2)
	override MPI=
endif

include Makefile.LINUX

include Makefile.ifort

ifdef MPI
	FC = mpif90
	CC = mpicc
endif

ifeq ($(USE_FFT),fftw)
	FFT_LIB   = -L${SCR}/comp/fftw/fftw-2.1.5/lib -lrfftw -lfftw
endif

ifdef USE_NETCDF
	NETCDF_INC = -I${SCR}/comp/netcdf-3.6.2/include
	NETCDF_LIB = -L${SCR}/comp/netcdf-3.6.2/lib -lnetcdf
endif
