# Compiler: GNU gcc
# This file is provided for some systems which do not have other
# C compiler.

CC = gcc

ifdef DEBUG
	CFLAGS += -g -Wall -fbounds-check
	COPTFLAGS +=
else
	ifdef OPT
		COPTFLAGS += -O3
	endif

	ifdef PROF
		CFLAGS += -pg
	endif
endif
