# Compiler: GNU gfortran/gcc

FC = gfortran
CC = gcc
F90FLAGS += -ffree-line-length-none
CPPFLAGS += -DCL=_GFORTRAN_ -DFILE=_GNU_ -DNO_SIZEOF

ifdef DBLE
	F90FLAGS += -fdefault-real-8
endif

ifdef STATIC
	LDFLAGS += -static
endif

ifdef DEBUG
	F90FLAGS += -g -Wall -fimplicit-none -fbounds-check
	F90OPTFLAGS =
	CFLAGS += -g -Wall -fbounds-check
	COPTFLAGS =
else
	ifdef OPT
		F90OPTFLAGS += -O3
		COPTFLAGS += -O3
	endif

	ifdef PROF
		F90FLAGS += -pg
		CFLAGS += -pg
	endif
endif
