
!> DO NOT EDIT THIS FILE
!! This file has been automatically generated using generate_diagnostics_config.rb

!> A module for handling the configuration of the diagnostics
!! module via the namelist diagnostics_config.
module diagnostics_config

  use simpledataio, only: sdatio_file
  use diagnostics_ascii, only: diagnostics_ascii_type

  public :: init_diagnostics_config
  public :: finish_diagnostics_config
  public ::diagnostics_type

  type diagnostics_type
   type(sdatio_file) :: sfile
   !type(sdatio_file) :: sfilemovie
   type(diagnostics_ascii_type) :: ascii_files
   !> Integer below gives the sdatio type 
   !! which corresponds to a gs2 real
   integer :: rtype
   integer :: istep
   logical :: create
   logical :: wryte
   logical :: distributed
   logical :: parallel
   logical :: exit
   logical :: vary_vnew_only
   real :: user_time
   real, dimension(:), allocatable :: fluxfac
   integer :: nwrite
   integer :: nwrite_large
   logical :: write_any
   logical :: print_line
   logical :: write_fields
   logical :: write_phi_over_time
   logical :: write_apar_over_time
   logical :: write_bpar_over_time
   logical :: write_movie
   logical :: write_moments
   logical :: write_fluxes
   logical :: write_fluxes_by_mode
   logical :: write_omega
   integer :: navg
   integer :: igomega
   real :: omegatinst
   real :: omegatol
   logical :: exit_when_converged
   logical :: write_verr
   logical :: write_max_verr
   integer :: ncheck
   logical :: write_heating
   logical :: write_ascii
   logical :: write_gyx
   logical :: write_g
   logical :: write_lpoly
  end type diagnostics_type


  private

contains
  subroutine init_diagnostics_config(gnostics)
    use file_utils, only: open_output_file
    type(diagnostics_type), intent(out) :: gnostics
    call read_parameters(gnostics)
  end subroutine init_diagnostics_config

  subroutine finish_diagnostics_config
  end subroutine finish_diagnostics_config

  subroutine read_parameters(gnostics)
    use file_utils, only: input_unit, error_unit, input_unit_exist
    use text_options, only: text_option, get_option_value
    use mp, only: proc0, broadcast
    implicit none
    type(diagnostics_type), intent(out) :: gnostics
    integer :: nwrite
    integer :: nwrite_large
    logical :: write_any
    logical :: print_line
    logical :: write_fields
    logical :: write_phi_over_time
    logical :: write_apar_over_time
    logical :: write_bpar_over_time
    logical :: write_movie
    logical :: write_moments
    logical :: write_fluxes
    logical :: write_fluxes_by_mode
    logical :: write_omega
    integer :: navg
    integer :: igomega
    real :: omegatinst
    real :: omegatol
    logical :: exit_when_converged
    logical :: write_verr
    logical :: write_max_verr
    integer :: ncheck
    logical :: write_heating
    logical :: write_ascii
    logical :: write_gyx
    logical :: write_g
    logical :: write_lpoly
    namelist /diagnostics_config/ &
      nwrite, &
      nwrite_large, &
      write_any, &
      print_line, &
      write_fields, &
      write_phi_over_time, &
      write_apar_over_time, &
      write_bpar_over_time, &
      write_movie, &
      write_moments, &
      write_fluxes, &
      write_fluxes_by_mode, &
      write_omega, &
      navg, &
      igomega, &
      omegatinst, &
      omegatol, &
      exit_when_converged, &
      write_verr, &
      write_max_verr, &
      ncheck, &
      write_heating, &
      write_ascii, &
      write_gyx, &
      write_g, &
      write_lpoly

    integer :: in_file
    logical :: exist

    if (proc0) then
      nwrite = 10
      nwrite_large = 100
      write_any = .true.
      print_line = .false.
      write_fields = .true.
      write_phi_over_time = .false.
      write_apar_over_time = .false.
      write_bpar_over_time = .false.
      write_movie = .false.
      write_moments = .true.
      write_fluxes = .true.
      write_fluxes_by_mode = .false.
      write_omega = .true.
      navg = 10
      igomega = 0
      omegatinst = 1.0e6
      omegatol = -0.001
      exit_when_converged = .true.
      write_verr = .true.
      write_max_verr = .false.
      ncheck = 10
      write_heating = .false.
      write_ascii = .true.
      write_gyx = .false.
      write_g = .false.
      write_lpoly = .false.

      in_file = input_unit_exist ("diagnostics_config", exist)
      if (exist) read (unit=in_file, nml=diagnostics_config)

      gnostics%nwrite = nwrite
      gnostics%nwrite_large = nwrite_large
      gnostics%write_any = write_any
      gnostics%print_line = print_line
      gnostics%write_fields = write_fields
      gnostics%write_phi_over_time = write_phi_over_time
      gnostics%write_apar_over_time = write_apar_over_time
      gnostics%write_bpar_over_time = write_bpar_over_time
      gnostics%write_movie = write_movie
      gnostics%write_moments = write_moments
      gnostics%write_fluxes = write_fluxes
      gnostics%write_fluxes_by_mode = write_fluxes_by_mode
      gnostics%write_omega = write_omega
      gnostics%navg = navg
      gnostics%igomega = igomega
      gnostics%omegatinst = omegatinst
      gnostics%omegatol = omegatol
      gnostics%exit_when_converged = exit_when_converged
      gnostics%write_verr = write_verr
      gnostics%write_max_verr = write_max_verr
      gnostics%ncheck = ncheck
      gnostics%write_heating = write_heating
      gnostics%write_ascii = write_ascii
      gnostics%write_gyx = write_gyx
      gnostics%write_g = write_g
      gnostics%write_lpoly = write_lpoly

    end if

    call broadcast (gnostics%nwrite)
    call broadcast (gnostics%nwrite_large)
    call broadcast (gnostics%write_any)
    call broadcast (gnostics%print_line)
    call broadcast (gnostics%write_fields)
    call broadcast (gnostics%write_phi_over_time)
    call broadcast (gnostics%write_apar_over_time)
    call broadcast (gnostics%write_bpar_over_time)
    call broadcast (gnostics%write_movie)
    call broadcast (gnostics%write_moments)
    call broadcast (gnostics%write_fluxes)
    call broadcast (gnostics%write_fluxes_by_mode)
    call broadcast (gnostics%write_omega)
    call broadcast (gnostics%navg)
    call broadcast (gnostics%igomega)
    call broadcast (gnostics%omegatinst)
    call broadcast (gnostics%omegatol)
    call broadcast (gnostics%exit_when_converged)
    call broadcast (gnostics%write_verr)
    call broadcast (gnostics%write_max_verr)
    call broadcast (gnostics%ncheck)
    call broadcast (gnostics%write_heating)
    call broadcast (gnostics%write_ascii)
    call broadcast (gnostics%write_gyx)
    call broadcast (gnostics%write_g)
    call broadcast (gnostics%write_lpoly)



  end subroutine read_parameters
end module diagnostics_config



