
!> DO NOT EDIT THIS FILE
!! This file has been automatically generated using generate_diagnostics_ascii.rb

!> A module for managing text-based output files 
!! for the new diagnostics module
module diagnostics_ascii


  !> Holds integers corresponding to the
  !! ascii output units
  type diagnostics_ascii_type
   integer :: fields
   integer :: phase
   integer :: heat
   integer :: heat2
   integer :: vres
   integer :: lpc
   integer :: vres2
   integer :: parity
   integer :: jext
   logical :: write_to_fields 
   logical :: write_to_phase 
   logical :: write_to_heat 
   logical :: write_to_heat2 
   logical :: write_to_vres 
   logical :: write_to_lpc 
   logical :: write_to_vres2 
   logical :: write_to_parity 
   logical :: write_to_jext 
  end type diagnostics_ascii_type



contains
  subroutine init_diagnostics_ascii(ascii_files)
    use file_utils, only: open_output_file
    type(diagnostics_ascii_type), intent(out) :: ascii_files
    if (ascii_files%write_to_fields) call open_output_file(ascii_files%fields, '.new.fields')
    if (ascii_files%write_to_phase ) call open_output_file(ascii_files%phase, '.new.phase')
    if (ascii_files%write_to_heat  ) call open_output_file(ascii_files%heat, '.new.heat')
    if (ascii_files%write_to_heat2 ) call open_output_file(ascii_files%heat2, '.new.heat2')
    if (ascii_files%write_to_vres  ) call open_output_file(ascii_files%vres, '.new.vres')
    if (ascii_files%write_to_lpc   ) call open_output_file(ascii_files%lpc, '.new.lpc')
    if (ascii_files%write_to_vres2 ) call open_output_file(ascii_files%vres2, '.new.vres2')
    if (ascii_files%write_to_parity) call open_output_file(ascii_files%parity, '.new.parity')
    if (ascii_files%write_to_jext  ) call open_output_file(ascii_files%jext, '.new.jext')
  end subroutine init_diagnostics_ascii

  subroutine finish_diagnostics_ascii(ascii_files)
    use file_utils, only: close_output_file
    type(diagnostics_ascii_type), intent(out) :: ascii_files
    if (ascii_files%write_to_fields) call close_output_file(ascii_files%fields)
    if (ascii_files%write_to_phase ) call close_output_file(ascii_files%phase)
    if (ascii_files%write_to_heat  ) call close_output_file(ascii_files%heat)
    if (ascii_files%write_to_heat2 ) call close_output_file(ascii_files%heat2)
    if (ascii_files%write_to_vres  ) call close_output_file(ascii_files%vres)
    if (ascii_files%write_to_lpc   ) call close_output_file(ascii_files%lpc)
    if (ascii_files%write_to_vres2 ) call close_output_file(ascii_files%vres2)
    if (ascii_files%write_to_parity) call close_output_file(ascii_files%parity)
    if (ascii_files%write_to_jext  ) call close_output_file(ascii_files%jext)
  end subroutine finish_diagnostics_ascii

end module diagnostics_ascii



